// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A = B o (CxD) " -write-source=SDDMM.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <complex.h>
#include <string.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#define TACO_DEREF(_a) (((___context___*)(*__ctx__))->_a)
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
int cmp(const void *a, const void *b) {
  return *((const int*)a) - *((const int*)b);
}
#endif

int compute(taco_tensor_t *A, taco_tensor_t *B) {
  double* restrict A_vals = (double*)(A->vals);
  double* restrict B_vals = (double*)(B->vals);

  double A_val = 0.0;
  double B_val = B_vals[0];

  A_val = B_val;

  A_vals[0] = A_val;
  return 0;
}

int assemble(taco_tensor_t *A, taco_tensor_t *B) {
  double* restrict A_vals = (double*)(A->vals);

  A_vals = (double*)malloc(sizeof(double) * 1);

  A->vals = (uint8_t*)A_vals;
  return 0;
}

int evaluate(taco_tensor_t *A, taco_tensor_t *B) {
  double* restrict A_vals = (double*)(A->vals);
  double* restrict B_vals = (double*)(B->vals);

  double A_val = 0.0;
  double B_val = B_vals[0];
  A_vals = (double*)malloc(sizeof(double) * 1);

  A_val = B_val;

  A_vals[0] = A_val;

  A->vals = (uint8_t*)A_vals;
  return 0;
}
