// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// taco "A(i,j) = B(i,j,k) * x(k) " -write-source=SparsityTTV.c
#ifndef TACO_C_HEADERS
#define TACO_C_HEADERS
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <complex.h>
#include <string.h>
#define TACO_MIN(_a,_b) ((_a) < (_b) ? (_a) : (_b))
#define TACO_MAX(_a,_b) ((_a) > (_b) ? (_a) : (_b))
#define TACO_DEREF(_a) (((___context___*)(*__ctx__))->_a)
#ifndef TACO_TENSOR_T_DEFINED
#define TACO_TENSOR_T_DEFINED
typedef enum { taco_mode_dense, taco_mode_sparse } taco_mode_t;
typedef struct {
  int32_t      order;         // tensor order (number of modes)
  int32_t*     dimensions;    // tensor dimensions
  int32_t      csize;         // component size
  int32_t*     mode_ordering; // mode storage ordering
  taco_mode_t* mode_types;    // mode storage types
  uint8_t***   indices;       // tensor index data (per mode)
  uint8_t*     vals;          // tensor values
  int32_t      vals_size;     // values array size
} taco_tensor_t;
#endif
int cmp(const void *a, const void *b) {
  return *((const int*)a) - *((const int*)b);
}
#endif

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *x) {
  int A1_dimension = (int)(A->dimensions[0]);
  int A2_dimension = (int)(A->dimensions[1]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[0]);
  int B2_dimension = (int)(B->dimensions[1]);
  int B3_dimension = (int)(B->dimensions[2]);
  double* restrict B_vals = (double*)(B->vals);
  int x1_dimension = (int)(x->dimensions[0]);
  double* restrict x_vals = (double*)(x->vals);

  #pragma omp parallel for schedule(static)
  for (int32_t pA = 0; pA < (A1_dimension * A2_dimension); pA++) {
    A_vals[pA] = 0.0;
  }

  #pragma omp parallel for schedule(runtime)
  for (int32_t i = 0; i < B1_dimension; i++) {
    for (int32_t j = 0; j < B2_dimension; j++) {
      int32_t pA2 = i * A2_dimension + j;
      int32_t pB2 = i * B2_dimension + j;
      for (int32_t k = 0; k < x1_dimension; k++) {
        int32_t pB3 = pB2 * B3_dimension + k;
        A_vals[pA2] = A_vals[pA2] + B_vals[pB3] * x_vals[k];
      }
    }
  }
  return 0;
}

int assemble(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *x) {
  int A1_dimension = (int)(A->dimensions[0]);
  int A2_dimension = (int)(A->dimensions[1]);
  double* restrict A_vals = (double*)(A->vals);

  A_vals = (double*)malloc(sizeof(double) * (A1_dimension * A2_dimension));

  A->vals = (uint8_t*)A_vals;
  return 0;
}

int evaluate(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *x) {
  int A1_dimension = (int)(A->dimensions[0]);
  int A2_dimension = (int)(A->dimensions[1]);
  double* restrict A_vals = (double*)(A->vals);
  int B1_dimension = (int)(B->dimensions[0]);
  int B2_dimension = (int)(B->dimensions[1]);
  int B3_dimension = (int)(B->dimensions[2]);
  double* restrict B_vals = (double*)(B->vals);
  int x1_dimension = (int)(x->dimensions[0]);
  double* restrict x_vals = (double*)(x->vals);

  int32_t A_capacity = A1_dimension * A2_dimension;
  A_vals = (double*)malloc(sizeof(double) * A_capacity);

  #pragma omp parallel for schedule(static)
  for (int32_t pA = 0; pA < A_capacity; pA++) {
    A_vals[pA] = 0.0;
  }

  #pragma omp parallel for schedule(runtime)
  for (int32_t i = 0; i < B1_dimension; i++) {
    for (int32_t j = 0; j < B2_dimension; j++) {
      int32_t pA2 = i * A2_dimension + j;
      int32_t pB2 = i * B2_dimension + j;
      for (int32_t k = 0; k < x1_dimension; k++) {
        int32_t pB3 = pB2 * B3_dimension + k;
        A_vals[pA2] = A_vals[pA2] + B_vals[pB3] * x_vals[k];
      }
    }
  }

  A->vals = (uint8_t*)A_vals;
  return 0;
}
